### ISSUE TITLE
Syntaxes settings issue causing silent failure / return

### ISSUE THREAD

**Issue by ollyollyollyltd** [Ennosuke/PHP-Codebeautifier#1]
Not an issue as such but took me some hair pulling to figure out, maybe someone else will 

By default the supported syntaxes setting is an array containing only `Packages/PHP/PHP.sublime-syntax`.  For some reason my ST3 uses `Packages/PHP/PHP.tmLanguage` instead, which was causing the run command to fail silently.  Adding 

```
"syntaxes": [
    "Packages/PHP/PHP.tmLanguage",
    "Packages/PHP/PHP.sublime-syntax"
]
```

to my user settings fixed the problem!

**Comment by curtisgibby** [comment]
+1 for @ollycross solution.
